language: python
os: linux
dist: xenial

python:
  - 3.8

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_NO_INHERIT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync --dev
  cp contrib/env-sample .env

script:
  - pipenv run flake8 pypro
  - pipenv run pytest --cov=pypro

after_success:
  - pipenv run codecov
